### ISSUE TITLE
Prologue and epilogue scripts on remote machine

### ISSUE THREAD

**Issue by harryjubb** [goerz/clusterjob#2]
Is it possible to run setup/teardown scripts on the remote machine when using `JobScript` with SSH?

I need to source a script on the remote that sets up the LSF environment before it will let me use `bsub`.

**Comment by goerz** [comment]
It is, indirectly, but only by defining a custom backend. Basically, you would have to subclass [LsfBackend](https://github.com/goerz/clusterjob/blob/develop/clusterjob/backends/lsf.py) and overwrite all the `cmd_` methods.

For example,

    class MyCustomLsfBackend(LsfBackend)

        def cmd_submit(self, jobscript):
            return 'my_bsub_wrapper.sh "%s"' % jobscript.filename

You would then put the script `my_bsub_wrapper.sh` somewhere in your `$PATH` on the cluster login node. It would contains whatever you need to do to actually submit to the scheduler (i.e., source your setup script and then call `bsub`). You'll have to register `MyCustomLsfBackend` with [`JobScript.register_backend`](http://clusterjob.readthedocs.io/en/latest/API/clusterjob.html#clusterjob.JobScript.register_backend) before using it. Sorry I haven't gotten around to writing the section on custom backends yet, but I hope you get the idea.

Does that solve your problem?

**Comment by harryjubb** [comment]
Hi, sorry for the delay, I went on leave for a few weeks and have only just come back to this.

That's really helpful, thank you. In the end I've "simplified" things by moving my pipeline off my laptop and onto a server that can `bsub` in it's own right, which is probably better in the long term. It's very helpful however to have the solution available; many thanks.
